/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.stackpointer.cier.modelo.tipo;

/**
 *
 * @author user
 */
public enum ParamEstandar {
    ESTANDAR_AULA,
    /*ESTANDAR_LOTE,
    ESTANDAR_CONSTRUCCION,   */ 
    ESTANDAR_MAXIMO_ALUMNOS_AULA,
    ESTANDAR_LABORATORIO_CIENCIAS,
    ESTANDAR_LABORATORIO_MULTIMEDIAL,
    ESTANDAR_LABORATORIO_COMPUTACION,
    ESTANDAR_BIBLIOTECA,
    ESTANDAR_SALA_MUSICA,
    ESTANDAR_SALA_ARTES,
    ESTANDAR_PLAYON_DEPORTIVO,
    ESTANDAR_EXPANSIONES_RECREATIVAS,
    ESTANDAR_SALON_USOS_MULTIPLES,
    ESTANDAR_PSICOPEDAGOGIA_ENFERMERIA,
    ESTANDAR_SERVICIOS_SANITARIOS,
    ESTANDAR_ALIMENTOS,
    ESTANDAR_OFICINA_ADMINISTRACION,
    ESTANDAR_INDICE_OCUPACION,
    ESTANDAR_INDICE_CONSTRUCCION,
    ESTANDAR_NIVEL_ACCESIBILIDAD,
    ESTANDAR_SANITARIOS;
}
