/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.stackpointer.cier.modelo.tipo;

/**
 *
 * @author nruiz
 */
public enum TipoIndicadorBID {
     
        TOTAL_ESTUDIANTES(1L),
        NUM_ESTABLECIMIENTOS(2L),
        NUM_PREDIOS(3L),
        PROPORCION_PREDIOS_PRESENTAN_RIESGOS_NATURALES(4L),
        POBLACION_AFECTADA_RIESGO_NATURAL(5L),
        PROPORCION_PREDIOS_PRESENTAN_RIESGOS_ANTROPICOS(6L),
        POBLACION_AFECTADA_RIESGO_ANTROPICO(7L),
        PROPORCION_PREDIOS_SIN_ACCESO_BUEN_ESTADO(8L),
        PROPORCION_PREDIOS_RUTA_EVALUACION_CRITICA(9L),
        PROPORCION_PREDIOS_CONDICION_ESTRUCTURA_CRITICA(10L),
        PROPORCION_PREDIOS_CON_PROBLEMAS_LEGALIZACION(11L),
        NUM_ESTUDIANTES_PREDIOS_PROBLEMAS_LEGALIZACION(12L),
        PROPORCION_PREDIOS_CONDICION_MATERIALIDAD_CRITICA(13L),
        PROPORCION_PREDIOS_DISPONIBILIDAD_AGUA(14L),
        PROPORCION_PREDIOS_AGUA_CONDICION_INSUFICIENTE(15L),
        PROPORCION_PREDIOS_DISPONIBILIDAD_ENERGIA_ELECTRICA(16L),
        PROPORCION_PREDIOS_ENERGIA_ELECTRICA_CONDICION_INSUFICIENTE(17L),
        ESTANDAR_AULA(18L),
        M2_ALUMNO_AULA(19L),
        ESTANDAR_SERVICIOS_SANITARIOS(20L),
        M2_ALUMNO_SERVICIOS_SANITARIOS(21L),
        UTILIZACION_ESTADAR_TOTAL(22L),
        CUPOS_TOTAL(23L),
        PROPORCION_PREDIOS_SATURADOS(24L),
        PROPORCION_PREDIOS_SUBUTILIZADOS(25L),
        AREA_PREDIO(26L),
        AREA_CONSTRUCCION_TOTAL(27L),
        CUMPLIMIENTO_NORMA_CONSTRUC_TOTAL(28L),
        ESTANDAR_INDICE_OCUPACION(29L),
        INDICE_OCUPACION(30L),
        ESTANDAR_CONSTRUCCION(31L),
        INDICE_CONSTRUCCION(32L);
        
        public Long id;

        TipoIndicadorBID(Long id) {
            this.id = id;
        }

        public Long getId() {
            return this.id;
        }
    
}
